In [2]:
import numpy as np

In [3]:
x=[[1,2],[3,4]]
total = 0
for i in x:
    total+= sum(i)
print(total)

10


In [4]:
x =[[1,2]],[[3,4]]
nx = np.array(x)

In [5]:
print(nx.sum())
print(nx.min())
print(nx.max())
print(nx.mean())
print(nx.std())
print(nx.var())

10
1
4
2.5
1.118033988749895
1.25


In [6]:
type(nx)

numpy.ndarray

In [7]:
nx.shape # shape of matrix

(2, 1, 2)

In [8]:
print(nx.size) # total elements
print(nx.dtype) # type of element

4
int64


In [9]:
# matrix of 3*3
y =[[1,2,3]],[[4,5,6]],[[7,8,9]]

functions to create matrix
- `arrange`: create a range of numbers
- `linspace`: create a matrix of specified number of matrix
- `ones`: create a matrrix of ones
- `zeros`: create a matrix of zeros
- `random.randiant`: create a matrix of random integers
- `random.rand`: create a matrix of random float
- `diag`: create a matrix with diagonal elelment

In [10]:
a = np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [11]:
np.arange(1,5,.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [12]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.random.randint(1,100,10)

array([52, 38, 32, 44, 61, 68, 29,  4, 97, 21], dtype=int32)

In [17]:
np.random.randint(1,100,10)

array([ 7, 43, 23,  3, 78, 76, 89,  3, 59,  3], dtype=int32)

In [18]:
np.random.rand(5) # num of elemnets

array([0.69663443, 0.22834338, 0.40935305, 0.03486603, 0.51128346])

In [19]:
np.random.rand(10,5) # 10*10 matrix

array([[0.09309873, 0.6160189 , 0.66840693, 0.84769085, 0.9294115 ],
       [0.94617636, 0.15079611, 0.78011453, 0.98607965, 0.49994655],
       [0.30365978, 0.50893855, 0.59783208, 0.70426111, 0.95071045],
       [0.86123874, 0.71483615, 0.58477819, 0.15609998, 0.37519687],
       [0.56824272, 0.41616355, 0.02679519, 0.33072104, 0.07576186],
       [0.02276011, 0.75738489, 0.44253493, 0.42236369, 0.09666262],
       [0.02995551, 0.73177846, 0.40332442, 0.91790096, 0.94719557],
       [0.51142488, 0.62233321, 0.31283979, 0.68402834, 0.38598127],
       [0.73559431, 0.13177301, 0.52903818, 0.82911673, 0.7618074 ],
       [0.19520258, 0.45548152, 0.27032486, 0.30429091, 0.45499676]])

In [20]:
np.set_printoptions(precision=3)
np.random.rand(10,5)

array([[0.724, 0.881, 0.541, 0.938, 0.245],
       [0.423, 0.334, 0.768, 0.25 , 0.119],
       [0.137, 0.939, 0.599, 0.623, 0.589],
       [0.65 , 0.289, 0.556, 0.564, 0.629],
       [0.829, 0.898, 0.994, 0.6  , 0.336],
       [0.487, 0.244, 0.728, 0.754, 0.619],
       [0.95 , 0.804, 0.434, 0.471, 0.192],
       [0.077, 0.749, 0.391, 0.398, 0.138],
       [0.365, 0.005, 0.898, 0.2  , 0.245],
       [0.226, 0.864, 0.295, 0.182, 0.121]])

In [21]:
x=[1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [22]:
# reshape 
np.arange(10).reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [23]:
x = np.linspace(1,5,25).reshape(5,5)

In [24]:
y = np.arange(1,26).reshape(5,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [25]:
y.transpose()

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

maths

In [26]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

[[7 5 7]
 [7 2 8]
 [3 9 3]]
[[6 4 7]
 [6 4 8]
 [6 1 2]]


In [27]:
print(a+b)
print(a*b)
print(a-b)
print(a/b)


[[13  9 14]
 [13  6 16]
 [ 9 10  5]]
[[42 20 49]
 [42  8 64]
 [18  9  6]]
[[ 1  1  0]
 [ 1 -2  0]
 [-3  8  1]]
[[1.167 1.25  1.   ]
 [1.167 0.5   1.   ]
 [0.5   9.    1.5  ]]


In [28]:
a.dot(b)

array([[114,  55, 103],
       [102,  44,  81],
       [ 90,  51,  99]], dtype=int32)

In [29]:
a *b # element wise multiplication

array([[42, 20, 49],
       [42,  8, 64],
       [18,  9,  6]], dtype=int32)

In [30]:
a +10 # add 10 to all numbers

array([[17, 15, 17],
       [17, 12, 18],
       [13, 19, 13]], dtype=int32)

stats

In [31]:
print(a.mean())

5.666666666666667


In [32]:
print(a.sum())
print(a.mean(axis=0)) # column  mean
print(a.mean(axis=1)) # row wise mean

51
[5.667 5.333 6.   ]
[6.333 5.667 5.   ]


In [33]:
np.sin(a)

array([[ 0.657, -0.959,  0.657],
       [ 0.657,  0.909,  0.989],
       [ 0.141,  0.412,  0.141]])

In [34]:
print(np.cos(a))
print(np.tan(a))

[[ 0.754  0.284  0.754]
 [ 0.754 -0.416 -0.146]
 [-0.99  -0.911 -0.99 ]]
[[ 0.871 -3.381  0.871]
 [ 0.871 -2.185 -6.8  ]
 [-0.143 -0.452 -0.143]]


In [35]:
print(np.exp(a))

[[1.097e+03 1.484e+02 1.097e+03]
 [1.097e+03 7.389e+00 2.981e+03]
 [2.009e+01 8.103e+03 2.009e+01]]


In [36]:
print(np.sqrt(a))
print(np.max(a))
print(np.min(a))

[[2.646 2.236 2.646]
 [2.646 1.414 2.828]
 [1.732 3.    1.732]]
9
2


In [37]:
x= np.random.randint(1,100,(2,5))
print(x)

[[21  6 59 72 88]
 [ 4 37  1 11 54]]


In [38]:
print(x.max()) 
print(x.argmax)
print(x.min())
print(x.argmin())

88
<built-in method argmax of numpy.ndarray object at 0x000002C2FEBF0690>
1
7


- slicing
  - 1D -[start:stop:step]
  - 2D -[row_start_stop:row)_step]

In [39]:
x = np.arange(1,11)
print(x[:5])
print(x[-5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [40]:
x =np.linspace(1,100,25).reshape(5,5).astype(int)
print(x)
print(x[0]) # row index 0
print(x[-1]) # last row
print(x[2]) # # row index 2
print(x[:3]) # row index 0 to 2
print(x[-2]) # last 2 rows

print(x[:0]) # column index 0
print(x[:,-1]) # last column

[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1  5  9 13 17]
[ 83  87  91  95 100]
[42 46 50 54 58]
[[ 1  5  9 13 17]
 [21 25 29 34 38]
 [42 46 50 54 58]]
[62 67 71 75 79]
[]
[ 17  38  58  79 100]


filtering

In [41]:
x>50 # boolean filter

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [42]:
x[x>50] # bradcasting

array([ 54,  58,  62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [43]:
x[(x>40) & (x<80)] 

array([42, 46, 50, 54, 58, 62, 67, 71, 75, 79])

In [44]:
x[x % 2 == 0]

array([ 34,  38,  42,  46,  50,  54,  58,  62, 100])

3rd party libaries

`plotly` - intrative plot using html

`matplotlib` - ploting libary for almost all type(image)

`seaborn` - plotting libary for statistiacl plots(extension of mat)

`spicy` - for support in seaborn

`nbformat` - for support in plotly

`statsmodels` - frp support in seaborn