In [5]:
import numpy as np

In [6]:
x=[[1,2],[3,4]]
total = 0
for i in x:
    total+= sum(i)
print(total)

10


In [7]:
x =[[1,2]],[[3,4]]
nx = np.array(x)

In [8]:
print(nx.sum())
print(nx.min())
print(nx.max())
print(nx.mean())
print(nx.std())
print(nx.var())

10
1
4
2.5
1.118033988749895
1.25


In [9]:
type(nx)

numpy.ndarray

In [10]:
nx.shape # shape of matrix

(2, 1, 2)

In [11]:
print(nx.size) # total elements
print(nx.dtype) # type of element

4
int64


In [12]:
# matrix of 3*3
y =[[1,2,3]],[[4,5,6]],[[7,8,9]]

functions to create matrix
- `arrange`: create a range of numbers
- `linspace`: create a matrix of specified number of matrix
- `ones`: create a matrrix of ones
- `zeros`: create a matrix of zeros
- `random.randiant`: create a matrix of random integers
- `random.rand`: create a matrix of random float
- `diag`: create a matrix with diagonal elelment

In [13]:
a = np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [17]:
np.arange(1,5,.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [19]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.random.randint(1,100,10)

array([57, 12, 71, 67, 16, 18, 28,  2, 47, 70], dtype=int32)

In [28]:
np.random.randint(1,100,10)

array([[ 5, -3, -5,  3, -2],
       [-5, -4, -3,  3, -5],
       [ 3,  3, -4, -3, -3],
       [ 0,  3, -5,  3,  4],
       [ 3,  4,  3, -4,  3]], dtype=int32)

In [29]:
np.random.rand(5) # num of elemnets

array([0.13736676, 0.80471921, 0.99480697, 0.00237488, 0.07354862])

In [31]:
np.random.rand(10,5) # 10*10 matrix

array([[0.28406305, 0.85242367, 0.07115519, 0.69297395, 0.89368402],
       [0.77856276, 0.54932038, 0.33402783, 0.24333587, 0.76393433],
       [0.47064728, 0.55353545, 0.33509305, 0.62712421, 0.99136691],
       [0.26942561, 0.57862446, 0.45364065, 0.54576146, 0.64474446],
       [0.06503608, 0.79197649, 0.34684978, 0.35065054, 0.75999856],
       [0.60950943, 0.35674579, 0.46267443, 0.98633027, 0.26729792],
       [0.12167229, 0.96176521, 0.22047869, 0.57810827, 0.13930178],
       [0.60830482, 0.39491645, 0.70546833, 0.05878117, 0.67030072],
       [0.13668214, 0.56651684, 0.89557652, 0.12219522, 0.17186196],
       [0.59238735, 0.22693862, 0.83453259, 0.78877741, 0.71948627]])

In [33]:
np.set_printoptions(precision=3)
np.random.rand(10,5)

array([[0.937, 0.171, 0.092, 0.655, 0.25 ],
       [0.779, 0.348, 0.166, 0.936, 0.826],
       [0.155, 0.435, 0.953, 0.434, 0.649],
       [0.478, 0.746, 0.5  , 0.414, 0.133],
       [0.257, 0.639, 0.456, 0.511, 0.215],
       [0.907, 0.097, 0.405, 0.499, 0.961],
       [0.197, 0.461, 0.792, 0.267, 0.771],
       [0.876, 0.334, 0.415, 0.128, 0.436],
       [0.34 , 0.012, 0.024, 0.237, 0.748],
       [0.248, 0.864, 0.222, 0.734, 0.599]])

In [34]:
x=[1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [37]:
# reshape 
np.arange(10).reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [42]:
x = np.linspace(1,5,25).reshape(5,5)

In [44]:
y = np.arange(1,26).reshape(5,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [45]:
y.transpose()

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

maths

In [47]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

[[7 1 3]
 [5 1 6]
 [2 4 5]]
[[6 2 8]
 [6 1 5]
 [8 9 8]]


In [49]:
print(a+b)
print(a*b)
print(a-b)
print(a/b)


[[13  3 11]
 [11  2 11]
 [10 13 13]]
[[42  2 24]
 [30  1 30]
 [16 36 40]]
[[ 1 -1 -5]
 [-1  0  1]
 [-6 -5 -3]]
[[1.167 0.5   0.375]
 [0.833 1.    1.2  ]
 [0.25  0.444 0.625]]


In [50]:
a.dot(b)

array([[72, 42, 85],
       [84, 65, 93],
       [76, 53, 76]], dtype=int32)

In [51]:
a *b # element wise multiplication

array([[42,  2, 24],
       [30,  1, 30],
       [16, 36, 40]], dtype=int32)

In [52]:
a +10 # add 10 to all numbers

array([[17, 11, 13],
       [15, 11, 16],
       [12, 14, 15]], dtype=int32)

stats

In [54]:
print(a.mean())

3.7777777777777777


In [58]:
print(a.sum())
print(a.mean(axis=0)) # column  mean
print(a.mean(axis=1)) # row wise mean

34
[4.667 2.    4.667]
[3.667 4.    3.667]


In [59]:
np.sin(a)

array([[ 0.657,  0.841,  0.141],
       [-0.959,  0.841, -0.279],
       [ 0.909, -0.757, -0.959]])

In [60]:
print(np.cos(a))
print(np.tan(a))

[[ 0.754  0.54  -0.99 ]
 [ 0.284  0.54   0.96 ]
 [-0.416 -0.654  0.284]]
[[ 0.871  1.557 -0.143]
 [-3.381  1.557 -0.291]
 [-2.185  1.158 -3.381]]


In [61]:
print(np.exp(a))

[[1096.633    2.718   20.086]
 [ 148.413    2.718  403.429]
 [   7.389   54.598  148.413]]


In [62]:
print(np.sqrt(a))
print(np.max(a))
print(np.min(a))

[[2.646 1.    1.732]
 [2.236 1.    2.449]
 [1.414 2.    2.236]]
7
1


In [64]:
x= np.random.randint(1,100,(2,5))
print(x)

[[65 79 31 28 50]
 [91 48 61 46 67]]


In [67]:
print(x.max()) 
print(x.argmax)
print(x.min())
print(x.argmin())

91
<built-in method argmax of numpy.ndarray object at 0x000001E53B096010>
28
3
